### PR TITLE
fix: two regressions from Chainguard base image switch

### PR DESCRIPTION
**Pull request by jglopez**
Two regressions from #45, both fixed here.

**Dev (`docker compose up` crash)**
Chainguard's node image sets `ENTRYPOINT ["node"]`, so `CMD ["npm", "run", "dev", ...]` was resolving to `node npm ...` — treating `npm` as a Node.js module path:

```
Error: Cannot find module '/app/npm'
```

Fix: `ENTRYPOINT []` in the dev stage clears the inherited entrypoint before CMD.

**Prod (SPA routing broken)**
Chainguard's nginx image ships a default server block at `/etc/nginx/conf.d/nginx.default.conf` with `server_name localhost` but no SPA fallback. Our config was written to `default.conf` (a separate file), so requests with `Host: localhost` matched Chainguard's block instead of ours — meaning `try_files` never ran and unknown routes returned 404.

Fix: copy our config to `nginx.default.conf` to replace Chainguard's default rather than adding a second competing server block.

Validated locally:
- `docker compose up --build` — Vite ready, port assigned by Docker
- `docker run -p 8080:8080 bill-split` — `/`, `/split`, `/nonexistent` all 200

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: Dockerfile [hunk 1]
```diff
@@ -9,7 +9,9 @@ COPY package.json package-lock.json ./
 RUN npm ci
 COPY . .
 EXPOSE 5173
+# Chainguard node sets ENTRYPOINT ["node"]; clear it so CMD runs as a shell command.
```
[the remark this answers is not in the document]
Comment (jglopez) [reply Dockerfile]: Good catch. Fixed in 890c1206bc45b7e4b5cf8a6be5b89249ce56ae5e — updated the comment to clarify it's exec form, not shell form.
